// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Teacher.proto

package com.mgw.proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mgw.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
