// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Teacher.proto

package com.mgw.proto;

public interface TeacherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mgw.proto.TeacherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string city = 3;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
